/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as BibliaRouteImport } from './routes/biblia'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PulpitoIdRouteImport } from './routes/pulpito.$id'
import { Route as EditorIdRouteImport } from './routes/editor.$id'
import { Route as ApiGenerateOutlineStreamRouteImport } from './routes/api.generate-outline-stream'
import { Route as ApiAnalyzeSermonStreamRouteImport } from './routes/api.analyze-sermon-stream'
import { Route as ApiAdaptSermonStreamRouteImport } from './routes/api.adapt-sermon-stream'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliaRoute = BibliaRouteImport.update({
  id: '/biblia',
  path: '/biblia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PulpitoIdRoute = PulpitoIdRouteImport.update({
  id: '/pulpito/$id',
  path: '/pulpito/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIdRoute = EditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateOutlineStreamRoute =
  ApiGenerateOutlineStreamRouteImport.update({
    id: '/api/generate-outline-stream',
    path: '/api/generate-outline-stream',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAnalyzeSermonStreamRoute = ApiAnalyzeSermonStreamRouteImport.update({
  id: '/api/analyze-sermon-stream',
  path: '/api/analyze-sermon-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdaptSermonStreamRoute = ApiAdaptSermonStreamRouteImport.update({
  id: '/api/adapt-sermon-stream',
  path: '/api/adapt-sermon-stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblia': typeof BibliaRoute
  '/importar': typeof ImportarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/adapt-sermon-stream': typeof ApiAdaptSermonStreamRoute
  '/api/analyze-sermon-stream': typeof ApiAnalyzeSermonStreamRoute
  '/api/generate-outline-stream': typeof ApiGenerateOutlineStreamRoute
  '/editor/$id': typeof EditorIdRoute
  '/pulpito/$id': typeof PulpitoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblia': typeof BibliaRoute
  '/importar': typeof ImportarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/adapt-sermon-stream': typeof ApiAdaptSermonStreamRoute
  '/api/analyze-sermon-stream': typeof ApiAnalyzeSermonStreamRoute
  '/api/generate-outline-stream': typeof ApiGenerateOutlineStreamRoute
  '/editor/$id': typeof EditorIdRoute
  '/pulpito/$id': typeof PulpitoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblia': typeof BibliaRoute
  '/importar': typeof ImportarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/adapt-sermon-stream': typeof ApiAdaptSermonStreamRoute
  '/api/analyze-sermon-stream': typeof ApiAnalyzeSermonStreamRoute
  '/api/generate-outline-stream': typeof ApiGenerateOutlineStreamRoute
  '/editor/$id': typeof EditorIdRoute
  '/pulpito/$id': typeof PulpitoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblia'
    | '/importar'
    | '/sitemap.xml'
    | '/api/adapt-sermon-stream'
    | '/api/analyze-sermon-stream'
    | '/api/generate-outline-stream'
    | '/editor/$id'
    | '/pulpito/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biblia'
    | '/importar'
    | '/sitemap.xml'
    | '/api/adapt-sermon-stream'
    | '/api/analyze-sermon-stream'
    | '/api/generate-outline-stream'
    | '/editor/$id'
    | '/pulpito/$id'
  id:
    | '__root__'
    | '/'
    | '/biblia'
    | '/importar'
    | '/sitemap.xml'
    | '/api/adapt-sermon-stream'
    | '/api/analyze-sermon-stream'
    | '/api/generate-outline-stream'
    | '/editor/$id'
    | '/pulpito/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliaRoute: typeof BibliaRoute
  ImportarRoute: typeof ImportarRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAdaptSermonStreamRoute: typeof ApiAdaptSermonStreamRoute
  ApiAnalyzeSermonStreamRoute: typeof ApiAnalyzeSermonStreamRoute
  ApiGenerateOutlineStreamRoute: typeof ApiGenerateOutlineStreamRoute
  EditorIdRoute: typeof EditorIdRoute
  PulpitoIdRoute: typeof PulpitoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblia': {
      id: '/biblia'
      path: '/biblia'
      fullPath: '/biblia'
      preLoaderRoute: typeof BibliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulpito/$id': {
      id: '/pulpito/$id'
      path: '/pulpito/$id'
      fullPath: '/pulpito/$id'
      preLoaderRoute: typeof PulpitoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$id': {
      id: '/editor/$id'
      path: '/editor/$id'
      fullPath: '/editor/$id'
      preLoaderRoute: typeof EditorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-outline-stream': {
      id: '/api/generate-outline-stream'
      path: '/api/generate-outline-stream'
      fullPath: '/api/generate-outline-stream'
      preLoaderRoute: typeof ApiGenerateOutlineStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-sermon-stream': {
      id: '/api/analyze-sermon-stream'
      path: '/api/analyze-sermon-stream'
      fullPath: '/api/analyze-sermon-stream'
      preLoaderRoute: typeof ApiAnalyzeSermonStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/adapt-sermon-stream': {
      id: '/api/adapt-sermon-stream'
      path: '/api/adapt-sermon-stream'
      fullPath: '/api/adapt-sermon-stream'
      preLoaderRoute: typeof ApiAdaptSermonStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliaRoute: BibliaRoute,
  ImportarRoute: ImportarRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAdaptSermonStreamRoute: ApiAdaptSermonStreamRoute,
  ApiAnalyzeSermonStreamRoute: ApiAnalyzeSermonStreamRoute,
  ApiGenerateOutlineStreamRoute: ApiGenerateOutlineStreamRoute,
  EditorIdRoute: EditorIdRoute,
  PulpitoIdRoute: PulpitoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
